services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
    dmzx.watermark.listener:
        class: dmzx\watermark\event\main_listener
        tags: [{ name: event.listener }]
    dmzx.watermark.controller.acp:
        class: dmzx\watermark\controller\acp_controller